### ISSUE TITLE
Some quick notes on `hypothesis.target()`

### ISSUE THREAD

**Issue by Zac-HD** [meeshkan/targeted-property-based-testing#1]
Hi there!  It's awesome to see people interested in PBT, and I thought I'd point out some of the ways that Hypothesis' implementation of targeting differs from the prior art.

> WHAT YOU LOSE IN TARGETED PBT
> - Complex data generators (recursive) -- nope, works fine in Hypothesis
> - Stateful testing (in regular form) -- also works fine in Hypothesis
> - Generator metrics -- I think this is statistics about what was generated?  Also works.
> - Shrinking (at least partially) -- is a separate phase, so no downside here
> - Variations in data -- yes, actually, details below

`PropEr` strongly prefers simulated annealing as a search technique; Hypothesis instead uses hill-climbing search.  This is considerably easier to implement, and allows us to ignore the actual value of the scores since we only need to compare them (very useful when they may be of wildly varying magnitude - any 64bit float!).

As far as I can tell `PropEr` only supports targeting a single metric per test, whereas Hypothesis allows you to target as many as you like.  We then maintain an [approximate pareto front](https://en.wikipedia.org/wiki/Pareto_efficiency#Pareto_frontier) and spend most of our time mutating from one of those inputs, which is a *very* cheap form of multi-objective optimisation.

Happy to chat if you have any questions :slightly_smiling_face:

**Comment by ksaaskil** [comment]
Hi @Zac-HD! Thanks a lot for your insightful feedback. This repository’s summary on targeted property-based testing is indeed heavily based on the corresponding chapter in the [Property-Based Testing with PropEr, Erlang, and Elixir](https://propertesting.com) book and, therefore, on the state-of-the-art presented therein. We would actually be interested in writing a blog post about targeted PBT with Hypothesis. Did you happen to see [this article](https://dev.to/meeshkan/from-1-to-10-000-test-cases-in-under-an-hour-a-beginner-s-guide-to-property-based-testing-1jf8) written by @carolstran and @fornwall already? To write such an article on targeted PBT, it's very valuable to better understand how Hypothesis does it under the hood!

A. Löscher’s papers provide quite deep understanding of how the PropEr implementation works under the hood. What do you think would be the best way to understand Hypothesis’ implementation at the same level? By starting reading source code? By asking questions in GitHub issues or IRC? 

The fact that recursive generators may lead to infinite loops in PropEr and that collecting metrics isn’t supported is indeed, as far as I know, related to implementation details in PropEr. Good to know Hypothesis currently doesn’t have any of those!  

As for shrinking, I put it there because my experiments involved rather complex data generation where shrinking wasn’t able to provide useful minimized inputs. Also when optimizing metrics such as execution time, one might want to disable shrinking completely to avoid the [threshold problem](https://hypothesis.works/articles/threshold-problem/). But you’re of course correct it’s not a problem of targeted PBT itself.

  As for stateful testing in Hypothesis, it would be awesome to come up with examples of using `RuleBasedStateMachine` with `target`, that might lead to very interesting tests!

Curious to hear what you think!

**Comment by Zac-HD** [comment]
Hmm.  We actually try to *avoid* describing the internals in detail, because they're subject to change - from a user perspective "Hypothesis tries to maximise the scores you pass to `target(score, label=...)` for each label" is literally all you need to know.  There are no config options that can make it perform better or worse!

If you want to see the implementation though, [here it is](https://github.com/HypothesisWorks/hypothesis/blob/adbd6db6a53f532bce58e01113228a1bf4d564ed/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L769-L810); reading the source code and comments is the best option available though I'm happy to answer questions here.

Hypothesis' targeting support is state-of-the-art in the sense that it works pretty well, works differently to PropEr's, and is the only non-PropEr implementation I know of.  We consider it good enough to ship to all our users, but there's certainly room for improvement (and probably a few papers on the topic).

Re: threshold problem, since [5.9.0 we print the highest observed scores for all failing tests]() which tends to help with the shrinking problem - at least when you `target(error); assert error < threshold`.  IMO the problem with targeting execution time is that it tends to be nondeterministic, and that makes replaying failures a real problem.  Something like "number of instructions executed" wouldn't have that problem either, though!

Re: trouble shrinking complex data, Hypothesis is very very good at this [partly because we use a different underlying architecture](https://hypothesis.works/articles/how-hypothesis-works/) and partly because shrinking is a large part of David's PhD research.  If you ever find a Hypothesis test that seems like it should shrink further, please open an issue and we'll look into it :grin: 

`RuleBasedStateMachine` + `target` sounds fun - no particular suggestions, just note that you'll want to call `target` in the `teardown` method as repeated calls are an error (to prevent accidental misuse).

**Comment by Zac-HD** [comment]
Closing this because there's no bug, I just wanted to say hi :slightly_smiling_face:
